name: Publish

concurrency: production

# This action should process only on push to 'production' branch
on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: "liberica"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build and Publish with Gradle
        run: ./gradlew clean build publishToJyrafRepo
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}